### PR TITLE
Reproduce shift down issue caused by navbar translucent

### PR DESCRIPTION
**Pull request by michael337663**
The shift down issue is happening when we set the navigation bar's translucent property to false.
Our project structure is render the page by adding the required controls accordingly.
on app.ts, will initiate a TestPage class, add action bar title, add the scroll view with text view inside.
On the TestPage class, will override the OnLoaded function, and inside the OnLoaded function will set the navigation bar's translucent to false, which will produce the shift down issue.

This is screenshot of using default translucent property:
translucent_true

This is screenshot of setting the nav bar translucent property to false:
translucent_false

Kindly help to check.
Thanks!

### CODE REVIEW

**Comment by michael337663** [comment]
FYI, this is an old issue in native iOS development. Here are some related articles.
https://stackoverflow.com/questions/18890192/container-view-getting-pushed-down-as-if-it-had-a-uinavigationbar
https://useyourloaf.com/blog/extra-space-when-embedding-table-views/
https://lonelycoding.com/uitableview-goes-under-translucent-navigation-bar/

We did tried a few solutions on our project, but still cannot fix the issue.

**Comment by vchimev** [comment]
Hey @michael337663,

thank you for the information.

This behavior is a bug. As a workaround, the `scrollableContent` property of `page` could be set to `false` as follows:
```
(<any>page).scrollableContent = false;
```

screen shot 2018-05-22 at 5 00 08 pm

**Comment by michael337663** [comment]
Hi @vchimev, thanks for your reply. 
I have tried to implement the scrollableContent = false setting to our project, but it still cannot solve the issue.
One thing to clarify is we have two places that set the translucent property.

- The first one for newly loaded page is at swift controller by setting navigationBar.isTranslucent = false
- While the other one for returning loaded page is in the new Page class similar as the code in the PR.

I'm trying to remove the code in the swift controller, and add the translucent = false to the Page class for both newly loaded and returning loaded page. In this case, the scrollableContent = false can fix the shift down issue, but looks like only for the first page. When I navigate to the other pages, some have shift up issue, some have shift down issue.
I'm trying to reproduce shift up and shift down issue upon navigation scenario on this sample project in this branch, will update here again.
Thanks!

**Comment by vchimev** [comment]
Hey @michael337663,

thank you for getting back to me.

Let me suggest one more possible workaround - if the page contains `ScrollView`, instead of setting `page.scrollableContent = false;` you could try to wrap the [`ScrolLView`](https://github.com/NativeScript/modal-navigation-demo/blob/vchimev/repro/app/app.ts#L18) in `GridLayout` for example.

**Comment by vchimev** [comment]
Hey @michael337663,

thank you for keeping me posted.

I am looking forward to your repro.

**Pull request closed without merging**
